# This is the workflow for deploying the smile docs

name: DEPLOY_DOCS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths:
      - "docs/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout main branch
        uses: actions/checkout@v3
        with: 
          ref: main
      
      # setup node.js
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
        
      # install node packages
      - name: Install node dependencies
        run: npm install

      - name: Rebuild docs
        run: npm run docs:build
        
      # Deploy files to web server
      - name: rsync to server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avrz --delete
          path: docs/.vitepress/dist/
          remote_path: ${{ secrets.DOCS_DEPLOY_PATH }}
          remote_host: ${{ secrets.DOCS_DEPLOY_HOST }}
          remote_port: ${{ secrets.DOCS_DEPLOY_PORT }}
          remote_user: ${{ secrets.DOCS_DEPLOY_USER }}
          remote_key:  ${{ secrets.DOCS_DEPLOY_KEY  }}